-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:e95a2a9853d7a4f37990fb82a4fe42c7$
-- 

return {
	texture = 'tilestexture.png',
	frames = {
			{
				name = "grass",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.515625, v0 = 0.261719, u1 = 0.640625, v1 = 0.324219 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hochhaus",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 192 },
				uvRect = { u0 = 0.0078125, v0 = 0.382812, u1 = 0.507812, v1 = 0.757812 },
				spriteSourceSize = { width = 128, height = 192 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hochhausstufe",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 192 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.507812, v1 = 0.378906 },
				spriteSourceSize = { width = 128, height = 192 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hospital",
				spriteColorRect = { x = 0, y = 10, width = 128, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.761719, u1 = 0.507812, v1 = 0.992188 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "house",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 96 },
				uvRect = { u0 = 0.515625, v0 = 0.00390625, u1 = 0.765625, v1 = 0.191406 },
				spriteSourceSize = { width = 64, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "leftstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.648438, v0 = 0.203125, u1 = 0.773438, v1 = 0.265625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lowerstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.515625, v0 = 0.195312, u1 = 0.640625, v1 = 0.257812 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rightstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.773438, v0 = 0.136719, u1 = 0.898438, v1 = 0.199219 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sidewalk",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.773438, v0 = 0.0703125, u1 = 0.898438, v1 = 0.132812 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "upperstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.773438, v0 = 0.00390625, u1 = 0.898438, v1 = 0.0664062 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

