-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:7672081735bba0057fe2635944d9cb04$
-- 

return {
	texture = 'tilestexture.png',
	frames = {
			{
				name = "hospital",
				spriteColorRect = { x = 0, y = 10, width = 128, height = 118 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.507812, v1 = 0.46875 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "house",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 96 },
				uvRect = { u0 = 0.0078125, v0 = 0.476562, u1 = 0.257812, v1 = 0.851562 },
				spriteSourceSize = { width = 64, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "leftstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.265625, v0 = 0.609375, u1 = 0.390625, v1 = 0.734375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lowerstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.265625, v0 = 0.476562, u1 = 0.390625, v1 = 0.601562 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rightstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.265625, v0 = 0.609375, u1 = 0.390625, v1 = 0.734375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sidewalk",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.140625, v0 = 0.859375, u1 = 0.265625, v1 = 0.984375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "upperstreet",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.0078125, v0 = 0.859375, u1 = 0.132812, v1 = 0.984375 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

